/**
 * Human decision route (Phase 9).
 *
 * POST /api/human-decision
 * Body: { context, decision, reason, risk }
 *   - context : the trade context the decision belongs to (asset, direction,
 *               thesis, timeframe, entryPrice, invalidationPrice, riskAmount,
 *               confidence, existingPosition).
 *   - decision: REQUIRED. One of TAKE / WAIT / SKIP. There is no default.
 *   - reason  : REQUIRED. The trader's own free-text explanation. Trimmed
 *               before validation, stored verbatim.
 *   - risk    : OPTIONAL. The Phase 6 risk result, CARRIED THROUGH for the
 *               record. It is never recalculated here.
 *
 * This endpoint records a human decision. It does not make one.
 *
 * Design rules:
 *   - This route DOES return 400 for an invalid decision, unlike the analysis
 *     routes. That difference is deliberate and is the whole point of the
 *     stage: the analysis routes answer "we could not get this data, here is
 *     the honest state", whereas this route answers "you have not given me a
 *     recordable decision yet". A missing decision or an empty reason is a
 *     validation failure, because silently storing a default would fabricate
 *     the trader's intent — the one thing this phase must never invent.
 *   - 400 responses still carry a well-formed DECISION REQUIRED record, so the
 *     UI has something consistent to render alongside the field errors.
 *   - The handler never returns 500.
 *   - The timestamp is generated server-side. A client-supplied time is ignored.
 *   - No provider is contacted, no model is called, nothing is executed, and no
 *     order, wallet or exchange action is reachable from here.
 *   - No secrets are read or exposed.
 */

import { Router } from 'express';
import {
  runHumanDecision,
  pendingDecision,
  DECISIONS,
  REASON_MIN_LENGTH,
  REASON_MAX_LENGTH,
} from '../services/humanDecision.js';

const router = Router();

router.post('/human-decision', (req, res) => {
  const body = req.body && typeof req.body === 'object' ? req.body : {};

  let result;
  try {
    result = runHumanDecision({
      decision: body.decision,
      reason: body.reason,
      context: body.context || body,
      risk: body.risk || null,
    });
  } catch (e) {
    // The service is pure, so this should be unreachable. If it ever happens the
    // honest answer is "nothing was recorded", never a fabricated decision.
    return res.status(200).json({
      status: 'error',
      message: `The decision could not be recorded: ${e?.message || e}`,
      ...meta(),
    });
  }

  if (!result.ok) {
    return res.status(400).json({
      status: 'invalid',
      message: 'A decision and your reason for it are both required.',
      errors: result.errors,
      record: result.record,
      ...meta(),
    });
  }

  return res.status(201).json({
    status: 'recorded',
    message:
      'Your decision has been recorded. TradeGuard recorded the choice and the reason you gave — it ' +
      'did not make the decision and does not recommend one.',
    record: result.record,
    ...meta(),
  });
});

/**
 * Static description of the endpoint's contract, returned with every response so
 * the UI never has to hard-code the vocabulary or infer what was done.
 */
function meta() {
  return {
    options: [...DECISIONS],
    reason: { required: true, minLength: REASON_MIN_LENGTH, maxLength: REASON_MAX_LENGTH },
    sources: {
      decision: 'Recorded by the trader — TradeGuard does not choose, suggest or score this',
      reason: 'Written by the trader — never generated, completed or edited by TradeGuard',
      trade: 'Carried through from the submitted trade context',
      risk: 'TradeGuard deterministic risk engine, Phase 6 (reused unchanged, never recalculated here)',
      timestamp: 'Generated by the server when the decision was recorded',
      execution: 'None — no order was placed, no exchange was contacted, nothing was executed',
    },
    generatedAt: new Date().toISOString(),
  };
}

export { pendingDecision };
export default router;
