/**
 * Human decision service tests (Phase 9).
 *
 * The service RECORDS the trader's decision. These tests exist mostly to prove
 * the things it must never do: choose, suggest, score, generate a reason,
 * invent a default, recalculate risk, or execute anything.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  runHumanDecision,
  validateDecision,
  buildDecisionRecord,
  pendingDecision,
  cleanDecisionContext,
  DECISION_STATUS,
  DECISION_STATUS_LABELS,
  DECISIONS,
  DECISION_HINTS,
  DECISION_OWNERSHIP_NOTICE,
  DECISION_METHOD_NOTE,
  DECISION_DISCLAIMER,
  DECISION_LIMITATIONS,
  RECORDED_PREFIX,
  REASON_MIN_LENGTH,
  REASON_MAX_LENGTH,
} from '../services/humanDecision.js';
import { runRiskAssessment } from '../services/riskEngine.js';

// --- fixtures ---------------------------------------------------------------

/** The exact manual-test trade: bullish rNVDA 100/95/50 -> 5 / 10 / 50. */
const CONTEXT = {
  asset: 'rNVDA',
  direction: 'bullish',
  thesis:
    'I think rNVDA will continue higher over the next few days because the current momentum is bullish and the price may continue to push higher if it holds above the key support area.',
  timeframe: 'swing',
  entryPrice: 100,
  invalidationPrice: 95,
  riskAmount: 50,
  confidence: 7,
  existingPosition: 'none',
};

/** The Phase 6 result for that trade, produced by the real engine. */
const RISK = runRiskAssessment(CONTEXT);

/** A reason the trader might genuinely write. Never generated by TradeGuard. */
const REAL_REASON =
  'Price held the support area on the last two sessions and momentum is still pointing up, so I am comfortable risking 50 on this setup.';

const FIXED_TIME = new Date('2026-09-19T20:00:00.000Z');

/** Convenience: run the service with a fixed clock. */
const decide = (over = {}) =>
  runHumanDecision({ decision: 'TAKE', reason: REAL_REASON, context: CONTEXT, risk: RISK, ...over }, FIXED_TIME);

const blobOf = (value) => JSON.stringify(value).toLowerCase();

// --- 1-3. the three options save --------------------------------------------

test('TAKE with a valid reason is recorded', () => {
  const res = decide({ decision: 'TAKE' });
  assert.equal(res.ok, true);
  assert.deepEqual(res.errors, {});
  assert.equal(res.record.status, DECISION_STATUS.RECORDED);
  assert.equal(res.record.statusLabel, 'DECISION RECORDED');
  assert.equal(res.record.decision, 'TAKE');
  assert.equal(res.record.reason, REAL_REASON);
});

test('WAIT with a valid reason is recorded', () => {
  const res = decide({ decision: 'WAIT' });
  assert.equal(res.ok, true);
  assert.equal(res.record.status, DECISION_STATUS.RECORDED);
  assert.equal(res.record.decision, 'WAIT');
  assert.equal(res.record.reason, REAL_REASON);
});

test('SKIP with a valid reason is recorded', () => {
  const res = decide({ decision: 'SKIP' });
  assert.equal(res.ok, true);
  assert.equal(res.record.status, DECISION_STATUS.RECORDED);
  assert.equal(res.record.decision, 'SKIP');
  assert.equal(res.record.reason, REAL_REASON);
});

test('every option in the vocabulary is recordable, and there are exactly three', () => {
  assert.deepEqual([...DECISIONS], ['TAKE', 'WAIT', 'SKIP']);
  for (const decision of DECISIONS) {
    const res = decide({ decision });
    assert.equal(res.ok, true, `${decision} should be recordable`);
    assert.equal(res.record.decision, decision);
    assert.ok(DECISION_HINTS[decision], `${decision} should have a hint`);
  }
});

test('the decision is recorded case-insensitively but stored canonically', () => {
  for (const raw of ['take', 'Take', '  take  ', 'TAKE']) {
    const res = decide({ decision: raw });
    assert.equal(res.ok, true, `${raw} should be accepted`);
    assert.equal(res.record.decision, 'TAKE', `${raw} should normalise to TAKE`);
  }
});

// --- 4. missing decision ----------------------------------------------------

test('a missing decision is rejected, never defaulted', () => {
  for (const decision of [undefined, null, '', '   ']) {
    const res = decide({ decision });
    assert.equal(res.ok, false, `${JSON.stringify(decision)} must not be accepted`);
    assert.ok(res.errors.decision, 'the decision error should be reported');
    assert.equal(res.record.decision, null, 'no decision may be invented');
    assert.equal(res.record.status, DECISION_STATUS.REQUIRED);
  }
});

test('the pending record is DECISION REQUIRED and is not a placeholder choice', () => {
  const pending = pendingDecision();
  assert.equal(pending.status, DECISION_STATUS.REQUIRED);
  assert.equal(pending.statusLabel, 'DECISION REQUIRED');
  assert.equal(pending.decision, null);
  assert.equal(pending.reason, null);
  assert.equal(pending.timestamp, null);
  assert.equal(pending.recordedPrefix, RECORDED_PREFIX);
  assert.equal(pending.executed, false);
  // The honest incomplete state still carries the guarantees.
  assert.equal(pending.ownershipNotice, DECISION_OWNERSHIP_NOTICE);
  assert.equal(pending.disclaimer, DECISION_DISCLAIMER);
  assert.deepEqual(pending.limitations, [...DECISION_LIMITATIONS]);
});

// --- 5-6. empty / whitespace-only reason ------------------------------------

test('an empty reason is rejected', () => {
  for (const reason of [undefined, null, '']) {
    const res = decide({ reason });
    assert.equal(res.ok, false, 'an empty reason must be rejected');
    assert.ok(res.errors.reason);
    assert.equal(res.record.reason, null, 'no reason may be invented');
  }
});

test('a whitespace-only reason is rejected', () => {
  for (const reason of [' ', '   ', '\t', '\n', ' \t \n ']) {
    const res = decide({ reason });
    assert.equal(res.ok, false, `${JSON.stringify(reason)} must be rejected`);
    assert.ok(res.errors.reason);
    assert.equal(res.record.reason, null);
  }
});

test('the reason is trimmed before it is stored or validated', () => {
  const res = decide({ reason: `   ${REAL_REASON}   ` });
  assert.equal(res.ok, true);
  assert.equal(res.record.reason, REAL_REASON, 'surrounding whitespace should be trimmed');

  // A reason that is only just long enough AFTER trimming must pass; the same
  // string padded with whitespace must not pass on the strength of the padding.
  const short = 'okay';
  const padded = `   ${short}   `;
  assert.equal(decide({ reason: short }).ok, true);
  assert.equal(decide({ reason: padded }).ok, true);
  assert.equal(decide({ reason: padded }).record.reason, short);
});

test('a too-short reason is rejected and a too-long reason is rejected', () => {
  const tooShort = 'a'.repeat(REASON_MIN_LENGTH - 1);
  const shortRes = decide({ reason: tooShort });
  assert.equal(shortRes.ok, false);
  assert.ok(shortRes.errors.reason);

  const tooLong = 'a'.repeat(REASON_MAX_LENGTH + 1);
  const longRes = decide({ reason: tooLong });
  assert.equal(longRes.ok, false);
  assert.ok(longRes.errors.reason);

  // The bounds themselves are inclusive.
  assert.equal(decide({ reason: 'a'.repeat(REASON_MIN_LENGTH) }).ok, true);
  assert.equal(decide({ reason: 'a'.repeat(REASON_MAX_LENGTH) }).ok, true);
});

// --- 7. unsupported decision value ------------------------------------------

test('an unsupported decision value is rejected', () => {
  const bad = ['BUY', 'SELL', 'PASS', 'HOLD', 'MAYBE', 'YES', 'NO', 'takee', '0', '1', 'true', '{}'];
  for (const decision of bad) {
    const res = decide({ decision });
    assert.equal(res.ok, false, `${decision} must be rejected`);
    assert.ok(res.errors.decision, `${decision} should report a decision error`);
    assert.equal(res.record.decision, null, `${decision} must not be stored`);
    assert.equal(res.record.status, DECISION_STATUS.REQUIRED);
  }
});

test('BUY / SELL / PASS are specifically not part of the vocabulary', () => {
  // These are instructions, not records of a human choice. The phase vocabulary
  // is deliberately TAKE / WAIT / SKIP and must not drift towards them.
  for (const forbidden of ['BUY', 'SELL', 'PASS']) {
    assert.equal(DECISIONS.includes(forbidden), false, `${forbidden} must not be an option`);
    assert.equal(decide({ decision: forbidden }).ok, false);
  }
});

test('a malformed request body is rejected rather than throwing', () => {
  for (const payload of [null, undefined, 'TAKE', 42, [], { decision: {} }, { decision: [] }]) {
    const res = runHumanDecision(payload, FIXED_TIME);
    assert.equal(res.ok, false, `${JSON.stringify(payload)} must be rejected`);
    assert.ok(res.errors.decision || res.errors.asset);
  }
});

test('a malformed trade context is rejected', () => {
  const res = decide({ context: { ...CONTEXT, entryPrice: 'abc' } });
  assert.equal(res.ok, false);
  assert.ok(res.errors.entryPrice);

  const nan = decide({ context: { ...CONTEXT, riskAmount: 'nope' } });
  assert.equal(nan.ok, false);
  assert.ok(nan.errors.riskAmount);

  const neg = decide({ context: { ...CONTEXT, invalidationPrice: '-5' } });
  assert.equal(neg.ok, false);
  assert.ok(neg.errors.invalidationPrice);

  const conf = decide({ context: { ...CONTEXT, confidence: 99 } });
  assert.equal(conf.ok, false);
  assert.ok(conf.errors.confidence);
});

test('a decision with no trade context at all is rejected', () => {
  const res = runHumanDecision({ decision: 'TAKE', reason: REAL_REASON, context: {} }, FIXED_TIME);
  assert.equal(res.ok, false);
  assert.ok(res.errors.asset);
  assert.equal(res.record.decision, null);
});

test('multiple problems are reported together, not one at a time', () => {
  const res = runHumanDecision({ decision: 'MAYBE', reason: '   ', context: {} }, FIXED_TIME);
  assert.equal(res.ok, false);
  assert.ok(res.errors.decision);
  assert.ok(res.errors.reason);
  assert.ok(res.errors.asset);
});

// --- 8. the record identifies the trade it belongs to -----------------------

test('the record preserves the full trade context it belongs to', () => {
  const res = decide();
  const { trade } = res.record;
  assert.equal(trade.asset, 'RNVDA');
  assert.equal(trade.direction, 'bullish');
  assert.equal(trade.thesis, CONTEXT.thesis);
  assert.equal(trade.timeframe, 'swing');
  assert.equal(trade.entryPrice, 100);
  assert.equal(trade.invalidationPrice, 95);
  assert.equal(trade.riskAmount, 50);
  assert.equal(trade.confidence, 7);
  assert.equal(trade.existingPosition, 'none');
});

test('the record is carried through as a whole and can be re-read', () => {
  const res = decide({ decision: 'WAIT' });
  // Round-tripping the record through JSON must lose nothing — this is the
  // shape a UI (or a future store) reads back.
  const reread = JSON.parse(JSON.stringify(res.record));
  assert.equal(reread.decision, 'WAIT');
  assert.equal(reread.reason, REAL_REASON);
  assert.equal(reread.timestamp, '2026-09-19T20:00:00.000Z');
  assert.equal(reread.trade.asset, 'RNVDA');
  assert.equal(reread.statusLabel, 'DECISION RECORDED');
});

test('the context is normalised the same way the Phase 1 validator does', () => {
  const { context, errors } = cleanDecisionContext({
    ...CONTEXT,
    asset: '  rnvda  ',
    direction: 'BULLISH',
    entryPrice: '$1,000',
  });
  assert.deepEqual(errors, {});
  assert.equal(context.asset, 'RNVDA');
  assert.equal(context.direction, 'bullish');
  assert.equal(context.entryPrice, 1000);
});

// --- 9. the timestamp is the system's own ----------------------------------

test('the timestamp is generated by the system', () => {
  const res = decide();
  assert.equal(res.record.timestamp, '2026-09-19T20:00:00.000Z');
  assert.equal(new Date(res.record.timestamp).toISOString(), res.record.timestamp);
});

test('a client-supplied timestamp is ignored', () => {
  // The record time is a system fact. A wrong client clock must not be able to
  // write it.
  const res = runHumanDecision(
    {
      decision: 'TAKE',
      reason: REAL_REASON,
      context: CONTEXT,
      risk: RISK,
      timestamp: '1999-01-01T00:00:00.000Z',
      recordedAt: '1999-01-01T00:00:00.000Z',
    },
    FIXED_TIME
  );
  assert.equal(res.record.timestamp, '2026-09-19T20:00:00.000Z');
});

test('the default clock is the real one and produces a valid ISO timestamp', () => {
  const before = Date.now();
  const res = decide();
  const after = Date.now();

  const withoutFixedClock = runHumanDecision({ decision: 'TAKE', reason: REAL_REASON, context: CONTEXT });
  const ts = Date.parse(withoutFixedClock.record.timestamp);
  assert.ok(Number.isFinite(ts));
  assert.ok(ts >= before - 1000 && ts <= after + 1000, 'the timestamp should be "now"');
  assert.equal(res.record.timestamp, FIXED_TIME.toISOString());
});

// --- risk figures are reused, never recalculated ---------------------------

test('the Phase 6 risk figures are reused unchanged: 5 / 10 / 50', () => {
  const res = decide();
  assert.equal(res.record.risk.priceRiskPerUnit, 5);
  assert.equal(res.record.risk.positionSize, 10);
  assert.equal(res.record.risk.definedRisk, 50);
  assert.equal(res.record.risk.riskBudget, 50);
  assert.equal(res.record.risk.entryPrice, 100);
  assert.equal(res.record.risk.invalidationPrice, 95);
  assert.equal(res.record.risk.state, 'available');
  assert.equal(res.record.risk.reused, true);
});

test('the recorded risk figures are identical to the engine\'s own output', () => {
  const res = decide();
  const calc = RISK.calculation;
  const inputs = RISK.inputs;

  // Figures the engine calculated, carried through untouched.
  for (const key of ['priceRiskPerUnit', 'positionSize', 'definedRisk', 'riskBudget']) {
    assert.equal(res.record.risk[key], calc[key], `${key} must match the engine exactly`);
  }
  // Levels the engine echoed back from the trader's own input.
  for (const key of ['entryPrice', 'invalidationPrice']) {
    assert.equal(res.record.risk[key], inputs[key], `${key} must match the engine exactly`);
  }
  assert.equal(res.record.risk.status, RISK.status);
  assert.equal(res.record.risk.statusLabel, RISK.statusLabel);

  // And the worked example the manual test expects, spelled out.
  assert.equal(res.record.risk.priceRiskPerUnit, 5);
  assert.equal(res.record.risk.positionSize, 10);
  assert.equal(res.record.risk.definedRisk, 50);
});

test('no risk result is recorded as unavailable rather than invented', () => {
  const res = runHumanDecision({ decision: 'TAKE', reason: REAL_REASON, context: CONTEXT }, FIXED_TIME);
  assert.equal(res.ok, true);
  assert.equal(res.record.risk.state, 'unavailable');
  assert.equal(res.record.risk.reused, false);
  assert.equal(res.record.risk.priceRiskPerUnit, null);
  assert.equal(res.record.risk.positionSize, null);
  assert.equal(res.record.risk.definedRisk, null);
  assert.ok(res.record.risk.reason);
});

test('an unreachable risk engine is recorded honestly, not as zeros', () => {
  const res = decide({ risk: { available: false, statusDetail: 'backend offline' } });
  assert.equal(res.record.risk.state, 'unavailable');
  assert.equal(res.record.risk.priceRiskPerUnit, null);
  assert.equal(res.record.risk.definedRisk, null);
  assert.match(res.record.risk.reason, /backend offline/);
});

test('an incomplete risk assessment is recorded as partial, not as a defined risk', () => {
  const incomplete = runRiskAssessment({ ...CONTEXT, entryPrice: null });
  assert.equal(incomplete.status, 'incomplete');
  const res = decide({ risk: incomplete });
  assert.equal(res.record.risk.state, 'partial');
  assert.equal(res.record.risk.definedRisk, null);
  assert.equal(res.record.risk.statusLabel, incomplete.statusLabel);
});

// --- the record belongs to the trader, not to TradeGuard -------------------

test('the record attributes the decision to the trader', () => {
  const res = decide();
  assert.equal(res.record.ownership, 'The decision was recorded by the trader.');
  assert.equal(res.record.recordedPrefix, 'You recorded:');
  assert.match(res.record.reasonSource, /not generated by TradeGuard/i);
  assert.equal(res.record.ownershipNotice, DECISION_OWNERSHIP_NOTICE);
});

test('the ownership notice says TradeGuard does not choose', () => {
  assert.match(DECISION_OWNERSHIP_NOTICE, /does not choose this for you/i);
  assert.match(DECISION_OWNERSHIP_NOTICE, /Record the decision you are making/i);
});

test('the record never claims TradeGuard recommends, suggests or scores', () => {
  for (const decision of DECISIONS) {
    const res = decide({ decision });
    const blob = blobOf(res.record);

    for (const forbidden of [
      'tradeguard recommends',
      'we recommend',
      'we suggest',
      'you should',
      'recommended action',
      'trade score',
      'score:',
      'confidence score',
      'ranking',
      'ranked',
    ]) {
      assert.ok(!blob.includes(forbidden), `"${forbidden}" must not appear for ${decision}`);
    }
  }
});

test('the record never expresses a verdict or a prediction', () => {
  // The service legitimately NAMES these things while denying them — "does not
  // tell you whether this is a good or bad trade", "not a prediction". Those
  // are the honest sentences we want. What must never appear is an ASSERTION of
  // a verdict, so each match is checked for a negation immediately before it.
  const NEGATORS = [
    'not ', "not'", "n't ", 'no ', 'never ', 'nor ', 'neither ', 'without ', 'does not', 'do not',
    'is not', 'are not', 'was not', 'cannot', 'rather than', 'instead of', 'neither',
  ];
  const NEGATION_WINDOW = 90;

  const blob = blobOf(decide().record);
  for (const forbidden of [
    /\bbuy\b/,
    /\bsell\b/,
    /\bpass\b/,
    'good trade',
    'bad trade',
    'safe trade',
    'worth taking',
    'likely to work',
    'probability',
    'win rate',
    'expected return',
    'guaranteed',
    'prediction',
    'will rise',
    'will fall',
  ]) {
    const re = forbidden instanceof RegExp
      ? new RegExp(forbidden.source, 'gi')
      : new RegExp(forbidden.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');

    let match;
    while ((match = re.exec(blob)) !== null) {
      const before = blob.slice(Math.max(0, match.index - NEGATION_WINDOW), match.index);
      const negated = NEGATORS.some((negator) => before.includes(negator));
      assert.ok(
        negated,
        `"${forbidden}" is asserted as a verdict — the service must only ever deny it. Context: …${blob.slice(
          Math.max(0, match.index - 70),
          match.index + 70
        )}…`
      );
      if (match[0].length === 0) re.lastIndex += 1; // guard against zero-width loops
    }
  }
});

test('the reason is stored verbatim and never rewritten', () => {
  // Includes the trader's own words, punctuation and casing — none of it touched.
  const reason = 'I am NOT taking this: rNVDA looks extended here, and I want to see it hold 95 first!!';
  const res = decide({ reason });
  assert.equal(res.record.reason, reason);
  assert.equal(res.record.reason.length, reason.length);
});

test('the reason cannot be swapped for the thesis or any other text', () => {
  // A defensive check that the service is not quietly substituting another field
  // when the reason is missing.
  const res = decide({ reason: '' });
  assert.equal(res.ok, false);
  assert.equal(res.record.reason, null);
  assert.notEqual(res.record.reason, CONTEXT.thesis);
});

test('nothing is executed and the record says so', () => {
  const res = decide();
  assert.equal(res.record.executed, false);
  assert.match(res.record.executionNotice, /Nothing has been executed/i);
  assert.match(res.record.executionNotice, /No order was placed/i);
});

test('the method note and disclaimer state the boundary', () => {
  const res = decide();
  assert.equal(res.record.methodNote, DECISION_METHOD_NOTE);
  assert.equal(res.record.disclaimer, DECISION_DISCLAIMER);
  assert.match(DECISION_METHOD_NOTE, /does not make the decision/i);
  assert.match(DECISION_DISCLAIMER, /not a trading instruction/i);
});

test('the standing limitations are always attached', () => {
  const res = decide();
  assert.deepEqual(res.record.limitations, [...DECISION_LIMITATIONS]);
  assert.ok(res.record.limitations.length >= 4);
  assert.ok(res.record.limitations.some((l) => /not a successful trade/i.test(l)));
  assert.ok(res.record.limitations.some((l) => /Nothing has been executed/i.test(l)));
});

// --- determinism and purity -------------------------------------------------

test('the service is deterministic for the same input and clock', () => {
  const a = decide({ decision: 'WAIT' });
  const b = decide({ decision: 'WAIT' });
  assert.deepEqual(a, b);
});

test('validation is pure and does not mutate its input', () => {
  const payload = { decision: 'take', reason: `  ${REAL_REASON}  `, context: { ...CONTEXT }, risk: RISK };
  const snapshot = JSON.parse(JSON.stringify(payload));
  validateDecision(payload);
  buildDecisionRecord(
    { decision: 'TAKE', reason: REAL_REASON, context: CONTEXT, riskContext: { state: 'available' } },
    FIXED_TIME
  );
  assert.deepEqual(payload, snapshot);
});

test('the service imports no provider and makes no network call', async () => {
  const src = await import('node:fs/promises').then((fs) =>
    fs.readFile(new URL('../services/humanDecision.js', import.meta.url), 'utf8')
  );
  // Strip the doc comment, which legitimately DISCUSSES what the module does not do.
  const code = src.replace(/\/\*\*[\s\S]*?\*\//g, '');
  for (const forbidden of ['fetch(', 'http://', 'https://', 'node-fetch', 'axios', 'process.env']) {
    assert.ok(!code.includes(forbidden), `humanDecision.js must not contain ${forbidden}`);
  }
});

// --- state vocabulary -------------------------------------------------------

test('there are exactly two deterministic decision states', () => {
  assert.deepEqual(Object.keys(DECISION_STATUS).sort(), ['RECORDED', 'REQUIRED']);
  assert.equal(DECISION_STATUS.REQUIRED, 'required');
  assert.equal(DECISION_STATUS.RECORDED, 'recorded');
  assert.deepEqual(Object.keys(DECISION_STATUS_LABELS).sort(), ['recorded', 'required']);
  assert.equal(DECISION_STATUS_LABELS.required, 'DECISION REQUIRED');
  assert.equal(DECISION_STATUS_LABELS.recorded, 'DECISION RECORDED');
});

test('there is no confidence, quality or recommendation score anywhere', () => {
  const res = decide();
  const keys = Object.keys(res.record).map((k) => k.toLowerCase());
  for (const forbidden of ['score', 'rating', 'recommendation', 'conviction', 'grade', 'probability', 'confidence']) {
    assert.ok(!keys.includes(forbidden), `the record must not carry a ${forbidden} field`);
  }
});
